agent:
  interface: &id001 !!python/object:smarts.core.agent_interface.AgentInterface
    accelerometer: !!python/object:smarts.core.agent_interface.Accelerometer {}
    action: &id010 !!python/object/apply:smarts.core.controllers.ActionSpaceType
    - 1
    agent_behavior: null
    debug: false
    done_criteria: !!python/object:smarts.core.agent_interface.DoneCriteria
      agents_alive: null
      collision: true
      not_moving: false
      off_road: true
      off_route: true
      on_shoulder: false
      wrong_way: false
    drivable_area_grid_map: false
    lidar: false
    max_episode_steps: 1000
    neighborhood_vehicles: &id011 !!python/object:smarts.core.agent_interface.NeighborhoodVehicles
      radius: 50
    ogm: false
    rgb: false
    road_waypoints: false
    vehicle_type: sedan
    waypoints: &id012 !!python/object:smarts.core.agent_interface.Waypoints
      lookahead: 50
env_config: &id015
  agent_specs:
    AGENT-0: !!python/object:smarts.core.agent.AgentSpec
      action_adapter: &id002 !!python/name:smarts.core.agent.%3Clambda%3E ''
      agent_builder: null
      agent_params: null
      info_adapter: &id003 !!python/name:smarts.core.agent.%3Clambda%3E ''
      interface: *id001
      observation_adapter: &id004 !!python/name:smarts.core.agent.%3Clambda%3E ''
      perform_self_test: false
      policy_builder: null
      policy_params: null
      reward_adapter: &id005 !!python/name:smarts.core.agent.%3Clambda%3E ''
    AGENT-1: !!python/object:smarts.core.agent.AgentSpec
      action_adapter: *id002
      agent_builder: null
      agent_params: null
      info_adapter: *id003
      interface: *id001
      observation_adapter: *id004
      perform_self_test: false
      policy_builder: null
      policy_params: null
      reward_adapter: *id005
    AGENT-2: !!python/object:smarts.core.agent.AgentSpec
      action_adapter: *id002
      agent_builder: null
      agent_params: null
      info_adapter: *id003
      interface: *id001
      observation_adapter: *id004
      perform_self_test: false
      policy_builder: null
      policy_params: null
      reward_adapter: *id005
    AGENT-3: !!python/object:smarts.core.agent.AgentSpec
      action_adapter: *id002
      agent_builder: null
      agent_params: null
      info_adapter: *id003
      interface: *id001
      observation_adapter: *id004
      perform_self_test: false
      policy_builder: null
      policy_params: null
      reward_adapter: *id005
  custom_config:
    action_adapter: !!python/name:baselines.marl_benchmark.common.discrete_action_adapter ''
    action_space: &id014 !!python/object:gym.spaces.discrete.Discrete
      _np_random: null
      dtype: !!python/object/apply:numpy.dtype
        args:
        - i8
        - 0
        - 1
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      n: 4
      shape: !!python/tuple []
    info_adapter: null
    name: FrameStack
    num_stack: 3
    observation_adapter: !!python/name:baselines.marl_benchmark.wrappers.rllib.frame_stack.func ''
    observation_space: &id013 !!python/object:gym.spaces.tuple.Tuple
      _np_random: null
      dtype: null
      shape: null
      spaces:
      - &id009 !!python/object:gym.spaces.dict.Dict
        _np_random: null
        dtype: null
        shape: null
        spaces: !!python/object/apply:collections.OrderedDict
        - - - distance_to_center
            - !!python/object:gym.spaces.box.Box
              _np_random: null
              bounded_above: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - &id006 !!python/name:numpy.ndarray ''
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - &id007 !!python/object/apply:numpy.dtype
                  args:
                  - b1
                  - 0
                  - 1
                  state: !!python/tuple
                  - 3
                  - '|'
                  - null
                  - null
                  - null
                  - -1
                  - -1
                  - 0
                - false
                - !!binary |
                  AA==
              bounded_below: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id007
                - false
                - !!binary |
                  AA==
              dtype: &id008 !!python/object/apply:numpy.dtype
                args:
                - f4
                - 0
                - 1
                state: !!python/tuple
                - 3
                - <
                - null
                - null
                - null
                - -1
                - -1
                - 0
              high: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id008
                - false
                - !!binary |
                  AACAfw==
              low: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id008
                - false
                - !!binary |
                  AACA/w==
              shape: !!python/tuple
              - 1
          - - goal_relative_pos
            - !!python/object:gym.spaces.box.Box
              _np_random: null
              bounded_above: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 2
                - *id007
                - false
                - !!binary |
                  AAA=
              bounded_below: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 2
                - *id007
                - false
                - !!binary |
                  AAA=
              dtype: *id008
              high: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 2
                - *id008
                - false
                - !!binary |
                  AACAfwAAgH8=
              low: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 2
                - *id008
                - false
                - !!binary |
                  AACA/wAAgP8=
              shape: !!python/tuple
              - 2
          - - heading_errors
            - !!python/object:gym.spaces.box.Box
              _np_random: null
              bounded_above: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 20
                - *id007
                - false
                - !!binary |
                  AAAAAAAAAAAAAAAAAAAAAAAAAAA=
              bounded_below: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 20
                - *id007
                - false
                - !!binary |
                  AAAAAAAAAAAAAAAAAAAAAAAAAAA=
              dtype: *id008
              high: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 20
                - *id008
                - false
                - !!binary |
                  AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8A
                  AIB/AACAfwAAgH8AAIB/AACAfwAAgH8=
              low: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 20
                - *id008
                - false
                - !!binary |
                  AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8A
                  AID/AACA/wAAgP8AAID/AACA/wAAgP8=
              shape: !!python/tuple
              - 20
          - - neighbor
            - !!python/object:gym.spaces.box.Box
              _np_random: null
              bounded_above: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 40
                - *id007
                - false
                - !!binary |
                  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
              bounded_below: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 40
                - *id007
                - false
                - !!binary |
                  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
              dtype: *id008
              high: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 40
                - *id008
                - false
                - !!binary |
                  AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8A
                  AIB/AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAA
                  gH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfwAAgH8AAIB/AACAfw==
              low: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 40
                - *id008
                - false
                - !!binary |
                  AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8A
                  AID/AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAA
                  gP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/wAAgP8AAID/AACA/w==
              shape: !!python/tuple
              - 40
          - - speed
            - !!python/object:gym.spaces.box.Box
              _np_random: null
              bounded_above: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id007
                - false
                - !!binary |
                  AA==
              bounded_below: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id007
                - false
                - !!binary |
                  AA==
              dtype: *id008
              high: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id008
                - false
                - !!binary |
                  AACAfw==
              low: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id008
                - false
                - !!binary |
                  AACA/w==
              shape: !!python/tuple
              - 1
          - - steering
            - !!python/object:gym.spaces.box.Box
              _np_random: null
              bounded_above: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id007
                - false
                - !!binary |
                  AA==
              bounded_below: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id007
                - false
                - !!binary |
                  AA==
              dtype: *id008
              high: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id008
                - false
                - !!binary |
                  AACAfw==
              low: !!python/object/apply:numpy.core.multiarray._reconstruct
                args:
                - *id006
                - !!python/tuple
                  - 0
                - !!binary |
                  Yg==
                state: !!python/tuple
                - 1
                - !!python/tuple
                  - 1
                - *id008
                - false
                - !!binary |
                  AACA/w==
              shape: !!python/tuple
              - 1
      - *id009
      - *id009
    reward_adapter: !!python/name:baselines.marl_benchmark.wrappers.rllib.frame_stack.func ''
  headless: true
  scenarios:
  - /src/baselines/marl_benchmark/scenarios/two_ways/bid_sv
  seed: 42
interface:
  action: *id010
  max_episode_steps: 1000
  neighborhood_vehicles: *id011
  waypoints: *id012
name: ppo-baseline
policy: !!python/tuple
- null
- *id013
- *id014
- custom_preprocessor: &id016 !!python/name:baselines.marl_benchmark.wrappers.rllib.frame_stack.TupleStackingPreprocessor ''
run:
  checkpoint_at_end: true
  checkpoint_freq: 2
  config:
    callbacks: !!python/name:baselines.marl_benchmark.common.SimpleCallbacks ''
    clip_param: 0.2
    env: !!python/name:baselines.marl_benchmark.wrappers.rllib.frame_stack.FrameStack ''
    env_config: *id015
    horizon: 1000
    lambda: 0
    log_level: WARN
    lr: 0.0001
    multiagent:
      policies:
        AGENT-0: !!python/tuple
        - null
        - *id013
        - *id014
        - agent_id: AGENT-0
          custom_preprocessor: *id016
        AGENT-1: !!python/tuple
        - null
        - *id013
        - *id014
        - agent_id: AGENT-1
          custom_preprocessor: *id016
        AGENT-2: !!python/tuple
        - null
        - *id013
        - *id014
        - agent_id: AGENT-2
          custom_preprocessor: *id016
        AGENT-3: !!python/tuple
        - null
        - *id013
        - *id014
        - agent_id: AGENT-3
          custom_preprocessor: *id016
      policy_mapping_fn: !!python/name:baselines.marl_benchmark.%3Clambda%3E ''
    num_gpus: 0
    num_sgd_iter: 10
    num_workers: 5
    sgd_minibatch_size: 32
  export_formats:
  - model
  - checkpoint
  local_dir: /src/baselines/marl_benchmark/log/results/run
  max_failures: 1000
  name: bid_sv-4
  restore: null
  resume: false
  run_or_experiment: &id017 !!python/name:ray.rllib.agents.trainer_template.PPO ''
  stop:
    time_total_s: 14400
trainer: *id017
